# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Get Chrome
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Install 
      run: sudo dpkg -i google-chrome-stable_current_amd64.deb
    - name: Complete install
      run: sudo apt-get install -f
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=test_results_$(date +%Y%m%d_%H%M%S).trx"
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: MetricConversionTests/TestResults/
